{% set name = "pbxproj" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fec5db4dcf6a160012ef349e6affbe9e5554fda7077a4725508ca5f012aa94d6

build:
  number: 0
  noarch: python
  entry_points:
    - pbxproj = pbxproj.__main__:main
    - pbxproj-file = pbxproj.pbxcli.pbxproj_file:main
    - pbxproj-flag = pbxproj.pbxcli.pbxproj_flag:main
    - pbxproj-folder = pbxproj.pbxcli.pbxproj_folder:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - coverage
    - nose
    - pip
    - python >=3.6
  run:
    - docopt
    - openstep-parser >=1.5.1
    - python >=3.6

test:
  imports:
    - pbxproj
    - pbxproj.pbxcli
  commands:
    - pip check
    - pbxproj --help
    - pbxproj-file --help
    - pbxproj-flag --help
    - pbxproj-folder --help
  requires:
    - pip

about:
  home: https://github.com/kronenthaler/mod-pbxproj
  license: MIT
  summary: XCode Project manipulation library for Python
  license_file: license.txt
  description: |
    This module can read, modify, and write a .pbxproj file from an Xcode 4+ projects. 

extra:
  recipe-maintainers:
    - cav71
